#!/usr/bin/env python
import os
import sys

from methods import print_error


libname = "EXTENSION-NAME"
projectdir = "project"

localEnv = Environment(tools=["default"], PLATFORM="")

# Build profiles can be used to decrease compile times.
# You can either specify "disabled_classes", OR
# explicitly specify "enabled_classes" which disables all other classes.
# Modify the example file as needed and uncomment the line below or
# manually specify the build_profile parameter when running SCons.

localEnv["build_profile"] = "build_profile.json"

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("godot-cpp") and os.listdir("godot-cpp")):
    print_error("""godot-cpp is not available within this folder, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

##FORCIBLY ENABLE EXCEPTIONS
if ARGUMENTS.get("disable_exceptions", None):
    raise ValueError("GDXMS2 does not currently support compiling without exceptions.")
ARGUMENTS["disable_exceptions"] = False

env = SConscript("godot-cpp/SConstruct", {"env": env, "customs": customs})

##INCLUDE PATHS
#env.Append(CCPATH=["../miniscript2/cpp/core/", "../miniscript2/cpp/editline/", "../miniscript2/cpp/"])
env.Append(CPPPATH=["../miniscript2/cpp/core/", "../miniscript2/cpp/editline/", "../miniscript2/generated/", "../miniscript2/cpp/"])

##SOURCE FILES
sources = Glob("src/*.c") + Glob("src/*.cc") + Glob("src/*.cxx") + Glob("src/*.cpp")

##MINISCRIPT FILES
miniscript2_sources = Glob("../miniscript2/cpp/core/*.c") + Glob("../miniscript2/cpp/core/*.cpp",
    exclude=["../miniscript2/cpp/core/test_simple.cpp"])

miniscript2_sources += Glob("../miniscript2/cpp/editline/*.c") + Glob("../miniscript2/cpp/editline/*.cpp")

miniscript2_sources += Glob("../miniscript2/generated/*.c") + Glob("../miniscript2/generated/*.cpp",
    exclude=["../miniscript2/generated/App.g.cpp", "../miniscript2/generated/ShellIntrinsics.g.cpp"])


miniscript2 = env.StaticLibrary("miniscript2", source=miniscript2_sources)


if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")
##handle computed goto based on compiler
#Clang
if "clang" in env["CXX"]:
    print("Using computed goto with Clang...")
    env.Append(CPPDEFINES=[('VM_USE_COMPUTED_GOTO', 1)])

#GCC
elif "g++" in env["CXX"]:
    print("Using computed goto with GCC...")
    env.Append(CPPDEFINES=[('VM_USE_COMPUTED_GOTO', 1)])

#MSVC
elif "cl" in env["CXX"]:
    print("Not using computed goto with MSVC...")
    env.Append(CPPDEFINES=[('VM_USE_COMPUTED_GOTO', 0)])

#Emscripten
elif "em++" in env["CXX"]:
    print("Not using computed goto with Emscripten...")
    env.Append(CPPDEFINES=[('VM_USE_COMPUTED_GOTO', 0)])

#Default
else:
    print("Not using computed goto with unknown compiler...")
    env.Append(CPPDEFINES=[('VM_USE_COMPUTED_GOTO', 0)])

# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = env['suffix'].replace(".dev", "").replace(".universal", "")

lib_filename = "{}{}{}{}".format(env.subst('$SHLIBPREFIX'), libname, suffix, env.subst('$SHLIBSUFFIX'))

library = env.SharedLibrary(
    "bin/{}/{}".format(env['platform'], lib_filename),
    source=sources,
    LIBS=[miniscript2]
)

copy = env.Install("{}/bin/{}/".format(projectdir, env["platform"]), library)

default_args = [library, copy]
Default(*default_args)
